### ISSUE TITLE
Header check

### ISSUE THREAD

**Issue by peaveyman** [madcowfred/GoPostStuff#14] opened 2015-02-15 13:21 UTC
Does GoPostStuff do a header check on the files it posts?

**Comment by thezoggy** [comment] 2015-02-15 21:28
nope

**Comment by peaveyman** [comment] 2015-02-15 22:19
Any plans to implement it?

**Comment by twiddern** [comment] 2015-02-15 22:41
This is a duplicate of #12

**Comment by madcowfred** [comment] 2015-02-16 02:23
Dupe #12

**Closed by madcowfred** 2015-02-16 02:23 UTC
Labels: duplicate
